export const ADD_INGREDIENT=' ADD_INGREDIENT';
export const REMOVE_INGREDIENT=' REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_ING_FAILED='FETCH_ING_FAILED';

export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED='PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
//for redirect after order
export const PURCHASE_INIT='PURCHASE_INIT';


